modLoader="javafml"
loaderVersion="[45,)"
license="Academic Free License v3.0"

[[mods]]
modId="minecraft_to_csv"
version="1.0.1"
displayName="Minecraft to CSV"
credits="Created using mod maker MCreator - https://mcreator.net/about, https://mcreator.net/plugin/64638/file-creator"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/mc-structure-to-csv"
authors="Sebastian Legieziński (seba0456), MCreator"
description="Simple mod that exports piece of your world to csv file."

[[dependencies.minecraft_to_csv]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




